### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by smarbos** [firnsy/BHack_Python_ILI9225#1]
I run $ python3 image.py
Im using Python 3.5.3 and has the ILI9225 connected to my raspberrypi 3 model B
and I get this error:
Traceback (most recent call last):
  File "image.py", line 23, in <module>
    import BHack_ILI9225 as TFT
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/BHack_ILI9225-1.0.0-py3.5.egg/BHack_ILI9225/__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/BHack_ILI9225-1.0.0-py3.5.egg/BHack_ILI9225/ILI9225.py", line 275
    self.command(ILI9225_HORIZONTAL_WINDOW_ADDR1).data(x1);
                                                          ^
TabError: inconsistent use of tabs and spaces in indentation

Let me know if I can give you any more information to reproduce or debug.

Thanks!

**Comment by koosthoe** [comment]
i am having the same issue. Found any fixes?

**Comment by Skiepp** [comment]
Guys, just run:
sed -i 's/\t/ /g' BHack_ILI9225/ILI9225.py

**(NOTE: insert 8 spaces between \t/ and /g)**

and then run setup.py
